### ISSUE TITLE
Hvordan strukture kode: per del i stack-en eller i kontext?

### ISSUE THREAD

**Issue by lordalek** [knowit/fagtur#1]
Strategi:
 - https://martinfowler.com/articles/micro-frontends.html

Stack:
- Frontend
  - Mobile
  - Web
- Backend
  - Databaser
  - Services

Kontekst:
- Servitrisen (Meny og spisested)
  - Services
  - Mobile
  - Web
    - JS
    - HTML
- Flokksamleren (Lokasjon og sånt)
  - Services
  - Streams
  - Mobile
  - Web

**Comment by frodeanonsen** [comment]
Stemmer for Stack approach, men database under service (en database skal alltid eies av _en_ service)

**Comment by lordalek** [comment]
Vil vi ikke bare ende opp med en struktur som dette da?

- Frontend
  - Web
    - Servitrisen
      - HTML
      - JS

- Backend
  - Service
    - Servitrisen
      - Db
      - Events

**Comment by frodeanonsen** [comment]
Dersom mobile / web kan utvikles som "micro-frontends" kan det fungere bra med **Kontekst** basert layout og.

Det viktigste er å velge en struktur, og begynne! :)
Man kan alltids refactor'e senere om det viser seg å være feil...

**Comment by lordalek** [comment]
Ok, da begynner vi med "stack"-layout.
